/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package argoview;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Florent Fayollas
 */
public class FenPrincipale extends javax.swing.JFrame {

    /**
     * Creates new form FenPrincipale
     */
    public FenPrincipale() {
        initComponents();
        
        lireDonnees();
    }

    /**
     * Fonction permettant de charger toutes les positions
     */
    private void lireDonnees() {
        gaia.lireDonnees();
        irchad.lireDonnees();
        teria3.lireDonnees();
        aquila.lireDonnees();
        leloki.lireDonnees();
        toms.lireDonnees();
        victor.lireDonnees();
        arcaique.lireDonnees();
        bandido.lireDonnees();
        flocon.lireDonnees();
        liriane.lireDonnees();
        malys.lireDonnees();
        neige.lireDonnees();
        una.lireDonnees();
        vanille.lireDonnees();
        ecume.lireDonnees();
        aura.lireDonnees();
        aurore.lireDonnees();
        nora.lireDonnees();
        vella.lireDonnees();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containChoixAnimal = new javax.swing.JPanel();
        boutonGaia = new javax.swing.JButton();
        boutonIrchad = new javax.swing.JButton();
        boutonTeria3 = new javax.swing.JButton();
        boutonAquila = new javax.swing.JButton();
        boutonLeloki = new javax.swing.JButton();
        boutonToms = new javax.swing.JButton();
        boutonVictor = new javax.swing.JButton();
        boutonBandido = new javax.swing.JButton();
        boutonArcaique = new javax.swing.JButton();
        boutonFlocon = new javax.swing.JButton();
        boutonMalys = new javax.swing.JButton();
        boutonEcume = new javax.swing.JButton();
        boutonVanille = new javax.swing.JButton();
        boutonLiriane = new javax.swing.JButton();
        boutonUna = new javax.swing.JButton();
        boutonNeige = new javax.swing.JButton();
        boutonNora = new javax.swing.JButton();
        boutonAura = new javax.swing.JButton();
        boutonAurore = new javax.swing.JButton();
        boutonVella = new javax.swing.JButton();
        containAnimal = new javax.swing.JPanel();
        ptsScroll = new javax.swing.JScrollPane();
        ptsTable = new javax.swing.JTable();
        containActs = new javax.swing.JPanel();
        majDonnees = new javax.swing.JButton();
        affDonnees = new javax.swing.JButton();
        containActsDonnees = new javax.swing.JPanel();
        affTrace = new javax.swing.JCheckBox();
        affPts = new javax.swing.JCheckBox();
        affNumPts = new javax.swing.JCheckBox();
        affDates = new javax.swing.JCheckBox();
        affFct = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ArgoView");
        setMaximumSize(new java.awt.Dimension(680, 700));
        setMinimumSize(new java.awt.Dimension(680, 700));
        setPreferredSize(new java.awt.Dimension(680, 700));
        setResizable(false);

        containChoixAnimal.setBorder(javax.swing.BorderFactory.createTitledBorder("Choix de l'animal"));
        containChoixAnimal.setPreferredSize(new java.awt.Dimension(200, 0));

        boutonGaia.setBackground(java.awt.Color.white);
        boutonGaia.setText("Baleine à bosse Gaïa");
        boutonGaia.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonGaia.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonGaia.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonGaia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonGaiaActionPerformed(evt);
            }
        });

        boutonIrchad.setBackground(java.awt.Color.white);
        boutonIrchad.setText("Baleine à bosse Irchad");
        boutonIrchad.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonIrchad.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonIrchad.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonIrchad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonIrchadActionPerformed(evt);
            }
        });

        boutonTeria3.setBackground(java.awt.Color.white);
        boutonTeria3.setText("Baleine à bosse Teria3");
        boutonTeria3.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonTeria3.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonTeria3.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonTeria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonTeria3ActionPerformed(evt);
            }
        });

        boutonAquila.setBackground(java.awt.Color.white);
        boutonAquila.setText("Manchot royal Aquila");
        boutonAquila.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonAquila.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonAquila.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonAquila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAquilaActionPerformed(evt);
            }
        });

        boutonLeloki.setBackground(java.awt.Color.white);
        boutonLeloki.setText("Manchot royal Leloki");
        boutonLeloki.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonLeloki.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonLeloki.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonLeloki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonLelokiActionPerformed(evt);
            }
        });

        boutonToms.setBackground(java.awt.Color.white);
        boutonToms.setText("Manchot royal Toms");
        boutonToms.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonToms.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonToms.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonToms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonTomsActionPerformed(evt);
            }
        });

        boutonVictor.setBackground(java.awt.Color.white);
        boutonVictor.setText("Manchot royal Victor");
        boutonVictor.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonVictor.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonVictor.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonVictor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonVictorActionPerformed(evt);
            }
        });

        boutonBandido.setBackground(java.awt.Color.white);
        boutonBandido.setText("Ours polaire Bandido");
        boutonBandido.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonBandido.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonBandido.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonBandido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonBandidoActionPerformed(evt);
            }
        });

        boutonArcaique.setBackground(java.awt.Color.white);
        boutonArcaique.setText("Ours polaire Arcaique");
        boutonArcaique.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonArcaique.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonArcaique.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonArcaique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonArcaiqueActionPerformed(evt);
            }
        });

        boutonFlocon.setBackground(java.awt.Color.white);
        boutonFlocon.setText("Ours polaire Flocon");
        boutonFlocon.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonFlocon.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonFlocon.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonFlocon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonFloconActionPerformed(evt);
            }
        });

        boutonMalys.setBackground(java.awt.Color.white);
        boutonMalys.setText("Ours polaire Malys");
        boutonMalys.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonMalys.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonMalys.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonMalys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonMalysActionPerformed(evt);
            }
        });

        boutonEcume.setBackground(java.awt.Color.white);
        boutonEcume.setText("Tortue Ecume");
        boutonEcume.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonEcume.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonEcume.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonEcume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEcumeActionPerformed(evt);
            }
        });

        boutonVanille.setBackground(java.awt.Color.white);
        boutonVanille.setText("Ours polaire Vanille");
        boutonVanille.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonVanille.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonVanille.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonVanille.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonVanilleActionPerformed(evt);
            }
        });

        boutonLiriane.setBackground(java.awt.Color.white);
        boutonLiriane.setText("Ours polaire Liriane");
        boutonLiriane.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonLiriane.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonLiriane.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonLiriane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonLirianeActionPerformed(evt);
            }
        });

        boutonUna.setBackground(java.awt.Color.white);
        boutonUna.setText("Ours polaire Una");
        boutonUna.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonUna.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonUna.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonUna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonUnaActionPerformed(evt);
            }
        });

        boutonNeige.setBackground(java.awt.Color.white);
        boutonNeige.setText("Ours polaire Neige");
        boutonNeige.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonNeige.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonNeige.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonNeige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonNeigeActionPerformed(evt);
            }
        });

        boutonNora.setBackground(java.awt.Color.white);
        boutonNora.setText("Eléphant de mer Nora");
        boutonNora.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonNora.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonNora.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonNora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonNoraActionPerformed(evt);
            }
        });

        boutonAura.setBackground(java.awt.Color.white);
        boutonAura.setText("Eléphant de mer Aura");
        boutonAura.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonAura.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonAura.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonAura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAuraActionPerformed(evt);
            }
        });

        boutonAurore.setBackground(java.awt.Color.white);
        boutonAurore.setText("Eléphant de mer Aurore");
        boutonAurore.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonAurore.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonAurore.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonAurore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonAuroreActionPerformed(evt);
            }
        });

        boutonVella.setBackground(java.awt.Color.white);
        boutonVella.setText("Eléphant de mer Vella");
        boutonVella.setMaximumSize(new java.awt.Dimension(200, 23));
        boutonVella.setMinimumSize(new java.awt.Dimension(200, 23));
        boutonVella.setPreferredSize(new java.awt.Dimension(200, 23));
        boutonVella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonVellaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containChoixAnimalLayout = new javax.swing.GroupLayout(containChoixAnimal);
        containChoixAnimal.setLayout(containChoixAnimalLayout);
        containChoixAnimalLayout.setHorizontalGroup(
            containChoixAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containChoixAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containChoixAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonGaia, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonTeria3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonAquila, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonLeloki, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonToms, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonVictor, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonArcaique, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonBandido, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonIrchad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonFlocon, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(containChoixAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boutonLiriane, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonNeige, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonUna, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonVanille, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonEcume, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonAura, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonAurore, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonNora, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonMalys, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonVella, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containChoixAnimalLayout.setVerticalGroup(
            containChoixAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containChoixAnimalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containChoixAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containChoixAnimalLayout.createSequentialGroup()
                        .addComponent(boutonLiriane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonMalys, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonNeige, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonUna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonVanille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonEcume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonAura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonAurore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonNora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(containChoixAnimalLayout.createSequentialGroup()
                        .addComponent(boutonGaia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonIrchad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonTeria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonAquila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonLeloki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonToms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonVictor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonArcaique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boutonBandido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(containChoixAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boutonFlocon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonVella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 34, Short.MAX_VALUE))
        );

        containAnimal.setBorder(javax.swing.BorderFactory.createTitledBorder("Données de positionnement relatives à l'animal"));
        containAnimal.setPreferredSize(new java.awt.Dimension(200, 0));

        ptsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ptsTable.setFocusable(false);
        ptsScroll.setViewportView(ptsTable);

        javax.swing.GroupLayout containAnimalLayout = new javax.swing.GroupLayout(containAnimal);
        containAnimal.setLayout(containAnimalLayout);
        containAnimalLayout.setHorizontalGroup(
            containAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ptsScroll)
        );
        containAnimalLayout.setVerticalGroup(
            containAnimalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ptsScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );

        containActs.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions sur les données"));
        containActs.setPreferredSize(new java.awt.Dimension(200, 0));

        majDonnees.setBackground(java.awt.Color.white);
        majDonnees.setText("Mettre à jour");
        majDonnees.setMaximumSize(new java.awt.Dimension(200, 23));
        majDonnees.setMinimumSize(new java.awt.Dimension(200, 23));
        majDonnees.setPreferredSize(new java.awt.Dimension(200, 23));
        majDonnees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majDonneesActionPerformed(evt);
            }
        });

        affDonnees.setBackground(java.awt.Color.white);
        affDonnees.setText("Afficher");
        affDonnees.setMaximumSize(new java.awt.Dimension(200, 23));
        affDonnees.setMinimumSize(new java.awt.Dimension(200, 23));
        affDonnees.setPreferredSize(new java.awt.Dimension(200, 23));
        affDonnees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affDonneesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containActsLayout = new javax.swing.GroupLayout(containActs);
        containActs.setLayout(containActsLayout);
        containActsLayout.setHorizontalGroup(
            containActsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containActsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containActsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(majDonnees, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(affDonnees, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containActsLayout.setVerticalGroup(
            containActsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containActsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(majDonnees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(affDonnees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        containActsDonnees.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions sur les données"));
        containActsDonnees.setPreferredSize(new java.awt.Dimension(200, 0));

        affTrace.setText("Afficher le tracé");
        affTrace.setBorderPaintedFlat(true);

        affPts.setText("Afficher les points");
        affPts.setBorderPaintedFlat(true);

        affNumPts.setText("Afficher les numéros des points");
        affNumPts.setBorderPaintedFlat(true);

        affDates.setText("Afficher les dates");
        affDates.setBorderPaintedFlat(true);

        affFct.setText("Fonction non implémentée");
        affFct.setBorderPaintedFlat(true);

        javax.swing.GroupLayout containActsDonneesLayout = new javax.swing.GroupLayout(containActsDonnees);
        containActsDonnees.setLayout(containActsDonneesLayout);
        containActsDonneesLayout.setHorizontalGroup(
            containActsDonneesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containActsDonneesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containActsDonneesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(affTrace)
                    .addComponent(affPts)
                    .addComponent(affNumPts)
                    .addComponent(affDates)
                    .addComponent(affFct))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        containActsDonneesLayout.setVerticalGroup(
            containActsDonneesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containActsDonneesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(affTrace)
                .addGap(18, 18, 18)
                .addComponent(affPts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(affNumPts)
                .addGap(18, 18, 18)
                .addComponent(affDates)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(affFct)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(containAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(containChoixAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(containActs, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(containActsDonnees, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(containActs, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(containActsDonnees, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                    .addComponent(containChoixAnimal, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(containAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boutonGaiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonGaiaActionPerformed
        ptsTable = gaia.getTableau();
        String[] test = {"entete", "entete2"};
        Object[][] obj = {{ "test", "aa" }, { "test", "aaa"} };
        ptsTable = new JTable(obj, test );
        ptsScroll = new JScrollPane(ptsTable);
    }//GEN-LAST:event_boutonGaiaActionPerformed

    private void boutonIrchadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonIrchadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonIrchadActionPerformed

    private void boutonTeria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonTeria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonTeria3ActionPerformed

    private void boutonAquilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAquilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonAquilaActionPerformed

    private void boutonLelokiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonLelokiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonLelokiActionPerformed

    private void boutonTomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonTomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonTomsActionPerformed

    private void boutonVictorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonVictorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonVictorActionPerformed

    private void boutonBandidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonBandidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonBandidoActionPerformed

    private void boutonArcaiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonArcaiqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonArcaiqueActionPerformed

    private void majDonneesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majDonneesActionPerformed
        majDonnees.setEnabled(false);
        majDonnees.setBackground(new Color(0, 175, 81));

        // Téléchargement des fichiers
        gaia.telechargerFichier();
        irchad.telechargerFichier();
        teria3.telechargerFichier();
        aquila.telechargerFichier();
        leloki.telechargerFichier();
        toms.telechargerFichier();
        victor.telechargerFichier();
        arcaique.telechargerFichier();
        bandido.telechargerFichier();
        flocon.telechargerFichier();
        liriane.telechargerFichier();
        malys.telechargerFichier();
        neige.telechargerFichier();
        una.telechargerFichier();
        vanille.telechargerFichier();
        ecume.telechargerFichier();
        aura.telechargerFichier();
        aurore.telechargerFichier();
        nora.telechargerFichier();
        vella.telechargerFichier();
        
        JOptionPane.showMessageDialog(this,
                "Mise à jour des fichiers de positionnement terminé !",
                "Mise à jour", JOptionPane.INFORMATION_MESSAGE);
        
        majDonnees.setEnabled(true);
        majDonnees.setText("Données à jour !");
        
        // Relecture des données
        lireDonnees();
    }//GEN-LAST:event_majDonneesActionPerformed

    private void affDonneesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affDonneesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_affDonneesActionPerformed

    private void boutonFloconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonFloconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonFloconActionPerformed

    private void boutonMalysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonMalysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonMalysActionPerformed

    private void boutonEcumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEcumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonEcumeActionPerformed

    private void boutonVanilleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonVanilleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonVanilleActionPerformed

    private void boutonLirianeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonLirianeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonLirianeActionPerformed

    private void boutonUnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonUnaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonUnaActionPerformed

    private void boutonNeigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonNeigeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonNeigeActionPerformed

    private void boutonNoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonNoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonNoraActionPerformed

    private void boutonAuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonAuraActionPerformed

    private void boutonAuroreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonAuroreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonAuroreActionPerformed

    private void boutonVellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonVellaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boutonVellaActionPerformed

    /*
        Variables
    */
    Animal gaia         = new Animal("Baleine à bosse Gaia", "gaia");
    Animal irchad       = new Animal("Baleine à bosse Irchad", "irchad");
    Animal teria3       = new Animal("Baleine à bosse Teria3", "teria3");
    Animal aquila       = new Animal("Manchot royal Aquila", "aquila");
    Animal leloki       = new Animal("Manchot royal Leloki", "leloki");
    Animal toms         = new Animal("Manchot royal Toms", "toms");
    Animal victor       = new Animal("Manchot royal Victor", "victor");
    Animal arcaique     = new Animal("Ours polaire Arcaique", "arcaique");
    Animal bandido      = new Animal("Ours polaire Bandido", "bandido");
    Animal flocon       = new Animal("Ours polaire Flocon", "flocon");
    Animal liriane      = new Animal("Ours polaire Liriane", "liriane");
    Animal malys        = new Animal("Ours polaire Malys", "malys");
    Animal neige        = new Animal("Ours polaire Neige", "neige");
    Animal una          = new Animal("Ours polaire Una", "una");
    Animal vanille      = new Animal("Ours polaire Vanille", "vanille");
    Animal ecume        = new Animal("Tortue Ecume", "ecume");
    Animal aura         = new Animal("Eléphant de mer Aura", "aura");
    Animal aurore       = new Animal("Eléphant de mer Autore", "aurore");
    Animal nora         = new Animal("Eléphant de mer Nora", "nora");
    Animal vella        = new Animal("Eléphant de mer Vella", "vella");
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox affDates;
    private javax.swing.JButton affDonnees;
    private javax.swing.JCheckBox affFct;
    private javax.swing.JCheckBox affNumPts;
    private javax.swing.JCheckBox affPts;
    private javax.swing.JCheckBox affTrace;
    private javax.swing.JButton boutonAquila;
    private javax.swing.JButton boutonArcaique;
    private javax.swing.JButton boutonAura;
    private javax.swing.JButton boutonAurore;
    private javax.swing.JButton boutonBandido;
    private javax.swing.JButton boutonEcume;
    private javax.swing.JButton boutonFlocon;
    private javax.swing.JButton boutonGaia;
    private javax.swing.JButton boutonIrchad;
    private javax.swing.JButton boutonLeloki;
    private javax.swing.JButton boutonLiriane;
    private javax.swing.JButton boutonMalys;
    private javax.swing.JButton boutonNeige;
    private javax.swing.JButton boutonNora;
    private javax.swing.JButton boutonTeria3;
    private javax.swing.JButton boutonToms;
    private javax.swing.JButton boutonUna;
    private javax.swing.JButton boutonVanille;
    private javax.swing.JButton boutonVella;
    private javax.swing.JButton boutonVictor;
    private javax.swing.JPanel containActs;
    private javax.swing.JPanel containActsDonnees;
    private javax.swing.JPanel containAnimal;
    private javax.swing.JPanel containChoixAnimal;
    private javax.swing.JButton majDonnees;
    private javax.swing.JScrollPane ptsScroll;
    private javax.swing.JTable ptsTable;
    // End of variables declaration//GEN-END:variables
}
