/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package argoview;

/**
 * Objet permettant d'afficher une fenêtre avec barre de progression
 * (pour les infos sur le téléchargement)
 * @author Florent Fayollas
 */
public class ProgressDownload extends javax.swing.JFrame {

    private int progression;
    
    /**
     * Creates new form ProgressDownload
     */
    public ProgressDownload() {
        progression = 0;
        initComponents();
    }
    
    /**
     * Permet de récupérer la progression actuelle
     * @return La progression actuelle
     */
    public int getProgression() {
        return this.progression;
    }
    
    /**
     * Permet de modifier la progression actuelle
     * @param progress  Nouvelle progression
     */
    public void setProgression( int progress ) {
        progression = progress;
        progressBar.setValue( progression );
        labelProgress.setText( Integer.toString(progression) + " %" );
    }
    
    /**
     * Permet d'ajouter du texte au champ de texte
     * @param txt   Texte à ajouter (ligne sautée à la fin)
     */
    public void addText( String txt ) {
        taskOutput.setText( taskOutput.getText() + txt + "\n" );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTask = new javax.swing.JScrollPane();
        taskOutput = new javax.swing.JTextArea();
        progressBar = new javax.swing.JProgressBar();
        labelProgress = new javax.swing.JLabel();

        setTitle("Progression du téléchargement");

        taskOutput.setEditable(false);
        taskOutput.setColumns(20);
        taskOutput.setRows(5);
        scrollTask.setViewportView(taskOutput);

        labelProgress.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelProgress.setText("100 %");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollTask)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProgress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollTask, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelProgress;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JScrollPane scrollTask;
    private javax.swing.JTextArea taskOutput;
    // End of variables declaration//GEN-END:variables
}
